apiVersion: v1
kind: Secret
metadata:
  name: payguard-secrets
  namespace: payguard
type: Opaque
stringData:
  DB_USERNAME: "payguard"
  DB_PASSWORD: "payguard"
  POSTGRES_USER: "payguard"
  POSTGRES_PASSWORD: "payguard"
