apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secret.yaml
  - 10-postgres-pvc.yaml
  - 11-postgres-deployment.yaml
  - 12-postgres-service.yaml
  - 20-redis-deployment.yaml
  - 21-redis-service.yaml
  - 30-payment-api-deployment.yaml
  - 31-payment-api-service.yaml
  - 40-worker-deployment.yaml
  - 50-mock-downstream-deployment.yaml
  - 51-mock-downstream-service.yaml
  - 60-chaos-injector-deployment.yaml
  - 61-chaos-injector-service.yaml
  - 70-otel-collector-configmap.yaml
  - 71-otel-collector-deployment.yaml
  - 72-otel-collector-service.yaml
  - 73-podmonitor-payment-api.yaml
  - 74-podmonitor-worker.yaml
  - 75-podmonitor-mock-downstream.yaml
  - 76-podmonitor-chaos-injector.yaml
  - 77-grafana-dashboard-configmap.yaml
