apiVersion: v1
kind: ConfigMap
metadata:
  name: payguard-config
  namespace: payguard
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/payments"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_DB: "payments"
  CHAOS_INJECTOR_URL: "http://chaos-injector:8080"
  MOCK_DOWNSTREAM_URL: "http://mock-downstream:8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_LOGS_EXPORTER: "none"
