apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: payment-api
  namespace: payguard
  labels:
    app: payment-api
spec:
  selector:
    matchLabels:
      app: payment-api
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s
      relabelings:
        - targetLabel: job
          replacement: payment-api
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: worker
  namespace: payguard
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s
      relabelings:
        - targetLabel: job
          replacement: worker
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mock-downstream
  namespace: payguard
  labels:
    app: mock-downstream
spec:
  selector:
    matchLabels:
      app: mock-downstream
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s
      relabelings:
        - targetLabel: job
          replacement: mock-downstream
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chaos-injector
  namespace: payguard
  labels:
    app: chaos-injector
spec:
  selector:
    matchLabels:
      app: chaos-injector
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s
      relabelings:
        - targetLabel: job
          replacement: chaos-injector
