apiVersion: v1
kind: Secret
metadata:
  name: payguard-secrets
  namespace: payguard
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.postgres.credentials.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
  POSTGRES_USER: {{ .Values.postgres.credentials.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
