apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: payguard
  labels:
    app: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payguard-config
                  key: SPRING_DATASOURCE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: payguard-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: payguard-config
                  key: REDIS_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payguard-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payguard-secrets
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: {{ .Values.worker.resources.requests.cpu }}
              memory: {{ .Values.worker.resources.requests.memory }}
            limits:
              cpu: {{ .Values.worker.resources.limits.cpu }}
              memory: {{ .Values.worker.resources.limits.memory }}
