apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SaintJude/payguard.git
    targetRevision: main
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: payguard
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: payment-api
      namespace: payguard
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: worker
      namespace: payguard
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
